### ISSUE TITLE
More flake8 plugins

### ISSUE THREAD

**Issue by Joonalai** [GispoCoding/cookiecutter-qgis-plugin#29]
**Expected behaviour**
The development of the new plugin should be as easy as possible. Some of this can be achieved with a good set of Flake8 plugins. 

**Current behaviour**
There are few plugins, but there could always be more...

**Additional context**
Here is a list of some of the useful plugins:

* flake8-print
* flake8-tidy-imports
* flake8-comprehensions
* flake8-simplify
* flake8-pytest-style
* flake8-pie

**Comment by Joonalai** [comment]
@LKajan, what do you think?

**Comment by LKajan** [comment]
We sure can add some more flake8 checks. I don't think the overhead of flake8 plugins is too much. I would still consider if the plugin is more just a personal preference or if it really helps to write better quality code.

From the proposed list of plugins I might question the usefullness of tidy-imports and maybe pie. And would probably add flake8-builtins, flake8-mutable, flake8-docstrings.

Here's a nice list of plugins that might be useful https://github.com/DmytroLitvinov/awesome-flake8-extensions. All the proposed plugins are on the list.

Maybe we could add a parameter to cookiecutter generation "Add code quality checks [Recommended, Minimal, None]".

**Comment by Joonalai** [comment]
Great idea! What do you propose to be included on each level of quality checks?
