### ISSUE TITLE
Different default name for processing folder

### ISSUE THREAD

**Issue by JuhoErvasti** [GispoCoding/cookiecutter-qgis-plugin#43]
**Expected behaviour**
The name of the folder for the processing provider algorithm modules should be something else other than "processing" to avoid confusion with the PyQGIS package. 

**Current behaviour**
Currently said folder is called "processing". This may cause a conflict or confusion with the QGIS package.

**Describe alternatives you've considered**
Name the folder after the plugin name, for example "myqgisplugin_processing".

**Comment by JuhoErvasti** [comment]
@nmaarnio thoughts?

**Comment by nmaarnio** [comment]
Good point! I agree that the current name may lead to confusion and/or errors. Somehow this did not cross my mind when I implemented the processing initialization.

I think the "myqgisplugin_processing" is an ok alternative for the folder name.

**Comment by LKajan** [comment]
Resolved by #46
