### ISSUE TITLE
Provider is not imported automatically when creating with submodule and processing

### ISSUE THREAD

**Issue by JuhoErvasti** [GispoCoding/cookiecutter-qgis-plugin#53]
**Describe the bug**
When you create a plugin with processing and the qgis_plugin_tools submodule, the processing provider is not included in `plugin.py`, see [here](https://github.com/GispoCoding/cookiecutter-qgis-plugin/blob/c7736110f09c181aa201df9765a4cbdc9f0e8d90/%7B%7Bcookiecutter.project_directory%7D%7D/plugin_templates/plugin_with_submodule.py.j2#L13).

This causes a NameError when trying to activate the plugin in QGIS.

**To Reproduce**
Create a plugin using the template, include processing and qgis plugin tools. Deploy the plugin, and try activating it.

**Expected behavior**
The Provider class should be imported. It is being referenced otherwise already.

**Comment by LKajan** [comment]
Resolved by #51
